on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push tr

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: create env file
        run: |
          touch .env
          echo HOST=${{ secrets.TR_HOST }} >> .env
          echo DOMAIN=${{ secrets.TR_DOMAIN }} >> .env

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files tr
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.TR_USER }}
          password: ${{ secrets.PASSWORD }}
          protocol: ${{ secrets.PROTOCOL }}
